## -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- ##
##                                  True False Quiz                                  ##
##                                    By Soapiee                                     ##
##                                                                                   ##
##       Message me on Discord for support, feature requests, bug reports, etc       ##
##                        discord.com/users/152044111153594369                       ##
## -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- ##

# Sends a message in console if there is an update available
update_notification: true

# These only apply if a game has an arena
arena_flags:
  allow_fall_damage: false # Should players take fall damage
  allow_pvp_damage: false # Can players deal damage to other players
  allow_hunger: false # Will a player lose hunger (they also cannot be satiated)
  allow_block_break: false # Can players break blocks
  allow_block_place: false # Can players place blocks
  allow_teleport: false # Should players be able to teleport

# Whether to save a backup of player inventories to a file when they are in an arena or not
save_player_inventories: false
# Whether to clear players inventories when they join an arena (it will be restored when they leave the arena)
empty_inv_on_arena_join: true
# Prevent players who are not in Survival mode to join games
enforce_survival_mode: true
# When a player joins the server, they are teleported here. NOTE: If false and your server crashes, players who were in arenas, will physically re-join inside the arena map/location
enforce_lobby_spawn: false

# Where you want players to be teleported to after they leave an arena, or where they spawn on server join (if the above setting is true)
lobby_spawn:
  world: world
  x: 0
  y: 64
  z: 0
  yaw: -180
  pitch: 0
  # List commands that you want to be disallowed whilst the player is in an arena
disallowed_commands:
  - '/example1'
#signs:
#  1: # EXAMPLE
#    game_ID: 1
#    material: OAK_WALL_SIGN
#    world: world
#    x: 2
#    y: 65
#    z: 2
#    facing: south
#    format:
#      - '%game_ID%'
#      - '%game_state%'
#      - ' '
#      - '%game_players%/%game_maxplayers%'
games:
  # # EXAMPLE 1 (without an arena)
  1:
    # Options: Recruiting or Closed
    state_on_startup: RECRUITING
    minimum_players: 5
    maximum_players: 20
    countdown_seconds: 10
    # Maximum amount of rounds to reach before ending the game. It will end earlier if there is 1 player remaining
    maximum_rounds: 10
    # Whether to announce the winner of a game to the whole server
    broadcast_winners: true
    reward:
      type: none
      #      reward: # EXAMPLE
      #      type: 'command' # Options: permission, currency, experience, item, command, none
      #      reward: 'xp give %player% 100'
      message: You gained some experience for winning
    arena: false
    # (in seconds) Only works when the arena option is false.
    # How long to wait before the game is opened
    #    schedule_delay: 300
    # (in seconds) How long the game remains open and in the recruiting state, before it closes again (will not close if the game is active).
    # Make sure this is longer than your countdown_seconds option. Defaults to 60 if this isn’t set.
#    schedule_resets: 120

#  # EXAMPLE 2 (with an arena)
#   2:
#     # Options: Recruiting or Closed
#     state_on_startup: RECRUITING
#     minimum_players: 5
#     maximum_players: 20
#     countdown_seconds: 60
#     maximum_rounds: 20
#     # Whether to announce the winner of a game to the whole server
#     broadcast_winners: true
#     reward:
#       type: 'item'
#       reward: oak_planks, 2
#       message: 'You won 2 oak planks'
#     arena: true
#     arena_options:
#       # Options: ‘both’, ‘chat’ or ‘hologram’
#       desc_option: hologram
#       # Enables the spectator system
#       spectators: true
#       # The spawn point for the hologram (Only works if desc_option is not ‘chat’
#       holo_location:
#         world: world
#         x: -50
#         y: 64
#         z: 64
#       # The spawn point where players get teleported to when they join the game/arena
#       spawn_point:
#         world: world
#         x: -50
#         y: 64
#         z: 64
#         yaw: -180
#         pitch: 0